# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  # Options include blue, cyan, green, indigo, purple, red, rose, sky, teal, and zinc.
  color: sky

# SEO
marketing:
  seo:
    site_type: ResearchOrganization
    local_business_type: ''
    org_name: 'AIR-DREAM Lab'
    description: 'Decision-making Research for Empowered AI Methods Lab.'
    twitter: ''
  analytics:
    google_analytics: 'G-NL9F8GHZ5L'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: center
    logo:
      # Logo text
      text: "AIR-DREAM Lab"
      # Logo filename in `assets/media/` folder
      filename: "icon.png"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true
#    logo:
#      text: ""

# Site footer
footer:
  block: minimal
  copyright:
    notice: '© {year} - AIR-DREAM Lab.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
